### ISSUE TITLE
potential build dependency issue

### ISSUE THREAD

**Issue by jipe4153** [NVIDIA/gvdb-voxels#1]
Hi! Thanks for the great talk at GTC Rama!

Just attempted building, did following:

git clone https://github.com/NVIDIA/gvdb-voxels.git
cd gvdb-voxels
mkdir build; cd build;
# Tried building gvdb library first
cmake ../source/gvdb_library/
# Got:
....
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xcursor_LIB (ADVANCED)
    linked by target "gvdb" in directory /home/jimmy/dev/gvdb-voxels/source/gvdb_library
X11_Xi_LIB (ADVANCED)
    linked by target "gvdb" in directory /home/jimmy/dev/gvdb-voxels/source/gvdb_library
X11_Xinerama_LIB (ADVANCED)
    linked by target "gvdb" in directory /home/jimmy/dev/gvdb-voxels/source/gvdb_library
X11_Xrandr_LIB (ADVANCED)
    linked by target "gvdb" in directory /home/jimmy/dev/gvdb-voxels/source/gvdb_library
....

So possibly I am missing some X11 dependency?

THanks!

**Comment by rchoetzlein** [comment]
Try the following:
> sudo apt-get install libxinerama-dev
> sudo apt-get install libxrandr-dev
> sudo apt-get install libxcursor-dev
> sudo apt-get install libx11-dev

I need to add these instructions to the READ_ME.txt. Will do asap. Thanks for the comment.

**Comment by MartinSamouiller** [comment]
Hello, 

I trying to build examples on ubuntu 16.04.
I have this error for all examples : 
_

> /usr/bin/ld: cannot find -lGLEW
> collect2: error: ld returned 1 exit status

_


Thanks,

**Comment by jipe4153** [comment]
Hmm, I haven't had time to look in detail but it looks like the cmake file doesn't contain a FindGLEW ? If It did cmake would have warned that it could not find GLEW or it would have found it and the correct path... right?

**Comment by MartinSamouiller** [comment]
Yes cmake file doesn't contain a FindGLEW.
I don't have find the error yet..
