### ISSUE TITLE
Undefined symbols when linking CUDA 10.1 on macOS 10.13

### ISSUE THREAD

**Issue by GreenEminence** [NVIDIA/gvdb-voxels#100]
I'm trying to compile this library on a Mac, after some modifications. I'm running into an issue when linking CUDA. It's a series of errors, but there's a common pattern, where I get:
```
Undefined symbols for architecture x86_64:
  "_cuArray3DCreate_v2", referenced from:
      nvdb::Allocator::AllocateTextureGPU(nvdb::DataPtr&, unsigned char, nvdb::Vector3D<int>, bool, unsigned long long) in gvdb_allocator.cpp.o
     (maybe you meant: __ZN6cudart24__fun_cuArray3DCreate_v2E)
```
Every undefined symbol ends with this `v2E` suffix, which appears to exist only on macOS platform. I tried the same on Windows and the linking process there is working fine. I'm not sure where this `E` comes from, couldn't find any info in the documentation. Is that a macOS-specific thing?

My environment:
- macOS 10.13.6
- CUDA 10.1
- CUDA driver 418.163

**Comment by NeilBickford-NV** [comment]
Hi GreenEminence!

This is interesting - do the samples that come with CUDA build for you (they should be in a folder such as `/Developer/NVIDIA/CUDA-10.1/samples`)? If so, then I'm guessing this is probably a bug in GVDB's new CMakeLists (at`source/gvdb_library/CMakeLists.txt`) - it's been tested on Windows and Ubuntu, but not on macOS yet.

Looking at the `CMakeLists.txt` file, I'm not seeing anything that stands out so far as being a bug, though - we enable CUDA support using
```
project(gvdb LANGUAGES CUDA CXX C)
```
configure the CUDA C++ standard using
```
if(NOT DEFINED CMAKE_CUDA_STANDARD)
    set(CMAKE_CUDA_STANDARD 11)
    set(CMAKE_CUDA_STANDARD_REQUIRED ON)
endif()
```
and then link CUDA using
```
if(WIN32)
    target_link_libraries(gvdb PUBLIC cuda.lib)
elseif(UNIX)
    find_package(X11 REQUIRED)
    target_link_libraries(gvdb
        PUBLIC  cuda
                ${X11_LIBRARIES})
endif()
```
This should hopefully go down the second branch - `UNIX` seems to be defined for macOS platforms in CMake, right? (Maybe there's something else that needs to be done in the CMake file for macOS platforms?)

Thank you!

**Comment by djspecialagent** [comment]
Would be so awesome if gvdb could be run on Mac!

**Comment by NeilBickford-NV** [comment]
Hi all - just checking in on the questions in the previous post to see if there have been any updates!

Also, just quickly checking - is it possible this could be a compiler mismatch? On Mac OS, CUDA 10.1 update 2 requires a specific version of Xcode and the Clang compiler and toolchain - see https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-mac-os-x/index.html#system-requirements. You can verify your installation using https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-mac-os-x/index.html#compiler-verification.

**Comment by NeilBickford-NV** [comment]
Ah, OK, sorry about that!
