### ISSUE TITLE
gInteractiveOptix

### ISSUE THREAD

**Issue by Delwin9999** [NVIDIA/gvdb-voxels#12]
In cuda_gvdb_raycast.cuh the function getLinearDepth uses the scn.* data structure only found under #define CUDA_PATHWAY without an ifdef guarding it.  This means that OPTIX_PATHWAY will not compile if you include cuda_gvdb_raycast.cuh which the gInteractiveOptix sample does.

**Comment by rchoetzlein** [comment]
Check out the latest GVDB Voxels 1.1 release where this should be resolved.
