### ISSUE TITLE
GVDB CUDA ERROR: the provided PTX was compiled with an unsupported toolchain

### ISSUE THREAD

**Issue by meherniger24** [NVIDIA/gvdb-voxels#120]
This error just hit out of nowhere. I was perfectly using gImportVDB module and other modules. Then, yesterday it started showing me this error when I run the gImportVDB module (and also for any other module).

> Debug Error!
> 
> C:\.....\gImportVDB.exe
> abort() has been called.
> 

And showing this GVDB CUDA Error:

> GVDB CUDA ERROR:
>   Launch status: the provided PTX was compiled with an unsupported toolchain.
>   Kernel status: no error
>   Caller: VolumeGVDB::LoadFunction
>   Call:   cuModuleLoad
>   Args:   cuda_gvdb_module.ptx
>   Generating assert so you can examine call stack.
> Assertion failed: 0, file C:\gvdb-2\gvdb-voxels2\source\gvdb_library\src\gvdb_allocator.cpp, line 1027

Any idea why this is happening? This is my configuration:

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:41:42_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

**Comment by NeilBickford-NV** [comment]
Hi meherniger24! Is it possible your system might have changed its graphics driver to an earlier version? CUDA 11.3 requires driver version at least 465.89 (on the compatibility platform it can go back to driver 456.38 though - see [this table](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions)).

The CUDA SDK installs the needed driver version by default, but if your system changed to an earlier version, you might get this error, and the solution is to update your drivers to a newer version. (See Robert Crovella's answer to a similar issue [here](https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292/2?u=nbickford).)

Thanks!

**Comment by meherniger24** [comment]
hey. thanks for helping. The problem is solved.
