### ISSUE TITLE
Hardware Requirement

### ISSUE THREAD

**Issue by jacquesvaneeden** [NVIDIA/gvdb-voxels#122]
I need a little help with hardware selection, all test systems we have done was done on systems with GTX 1070 GPUs. 
We have a number of systems using GDVB to roll out soon, hardware selection on the machines now quite a priority 

Only requirement listed in the documentation I could find "NVIDIA Kepler generation or later GPU"
Tests on Quadro M2000 don't work even for some of the small sample that ships with GVDB. The M2000 is Maxwell based which is successor to Kepler and should work or am I missing something?  
Will RTX 2070 & RTX 3070 do the trick?
What about Quadro RTX 4000?
What Nvidia CPU to use in laptops?

**Comment by NeilBickford-NV** [comment]
Hi Jacques! We should support the M2000; could you share what error you're getting when running the GVDB sample?

**Comment by jacquesvaneeden** [comment]
Hi Neil. After receiving your comment I went back to check, updated drives and validated the test environment. Got the M2000 working. (Painfully slow but working) Also got a Quadro RTX 4000 connected to a video wall with 4 screens. Works like a charm

If anybody else on here need to do hardware selection, this might be useful https://resources.nvidia.com/en-us-general-rtx/quadro-ampere-lineca 

Thanks for getting back
