### ISSUE TITLE
Compile g3DPrint

### ISSUE THREAD

**Issue by CChape** [NVIDIA/gvdb-voxels#13]
I'm using, Linux, and I follow your tutorial. I got a problem, for compile all the g3DPrint, gDepthMap... because, when I use make, I got an error that : "Unknown Platform", this error come when we call the platform.h (l. 184) define in sample_utils. I would know, how can I fix it? 
So the program recognize that I use GNUC as a compiler but he don't find a "signature" (__arm__). I put you a copy of my terminal. 

[ 14%] Building CXX object CMakeFiles/gDepthMap.dir/main_depthmap.cpp.o
In file included from /usr/local/gvdb/source/sample_utils/main.h:27:0,
                 from /usr/local/gvdb/source/gDepthMap/main_depthmap.cpp:9:
/usr/local/gvdb/source/sample_utils/platform.h:184:6: error: #error "Unknown platform"
 #    error "Unknown platform"

Thanks for your answer! 
Colin

**Comment by rchoetzlein** [comment]
You may be able to modify platform.h to enable your particular platform.

Notice line 124 checks for GNUC and then defines NV_GNUC if found. For some reason, that is not being enabled by your platform. You can modify this to make sure that NV_GNUC gets defined. There are further defines below (line 160) that check for arm, etc.

**Comment by NeilBickford-NV** [comment]
Hi CChape,

Just wanted to let you know that I'm closing this issue for now since no follow-up; please reopen this issue if there are any updates - thank you!
