### ISSUE TITLE
gFluidSurface fails on GTX 970 on Win10..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/gvdb-voxels#15]
testing new SDK 1.1 reléase on Windows 10 GTX 970 and 391.35 driver..
all samples work ok except: gFluidSurface.exe
it's due to 4gb GPU memory not enough?
thanks..
error log:
> FLUID SYSTEM, CUDA ERROR:
>   Launch status: unspecified launch failure
>   Kernel status: no error
>   Caller: FluidSystem::TransferFromCUDA
>   Call:   cuMemcpyDtoH
>   Args:   FPOS
> Error. Application will exit.

full log below:

> gFluidSurface.exe
> Reading TGA: arial.tga
> Creating OptiX context.
> Setting Ray Generation program.
>   Loading: optix_trace_primary.ptx, trace_primary
>   Loading: optix_trace_primary.ptx, exception
> Setting Miss program.
>   Loading: optix_trace_miss.ptx, miss
> Creating random number buffer.
> Creating Mesh intersection programs.
>   Loading: optix_mesh_intersect.ptx, mesh_intersect
>   Loading: optix_mesh_intersect.ptx, mesh_bounds
> Creating Volume intersection programs.
>   Loading: optix_vol_intersect.ptx, vol_intersect
>   Loading: optix_vol_intersect.ptx, vol_levelset
>   Loading: optix_vol_intersect.ptx, vol_deep
>   Loading: optix_vol_intersect.ptx, vol_bounds
> Creating OptiX Main Group and BVH.
> PERF_INIT: No CPU markers.
> PERF_INIT: Disabling GPU markers. Did not find nvToolsExt64_1.dll.
> PERF_INIT: Disabling perf. No CPU or GPU markers.
> Starting GVDB Voxels. ver 1.11
>  Creating Allocator..
>  Creating Scene..
>  Creating CUDPP..
> Starting Fluid System.
> Add Particles. Density: 400.000000, Spacing: 1.393426, PDist: 0.008008
> CUDA Config:
>   Pnts: 1500000, t:2930x512=1500160, Size:1500160
>   Grid: 1203052, t:2350x512=1203200, bufGrid:0, Res: 134x67x134
> Creating screen buffer. 1024 x 768
>   Loading: optix_trace_surface.ptx, trace_surface
>   Loading: optix_trace_surface.ptx, trace_shadow
> Adding GVDB Volume to OptiX graph.
> Validating OptiX.
> Update GVDB Volume.
> Rebuild Optix.. Done.
> Running..
> OptiX buffer size: 1024, 768
> FLUID SYSTEM, CUDA ERROR:
>   Launch status: unspecified launch failure
>   Kernel status: no error
>   Caller: FluidSystem::TransferFromCUDA
>   Call:   cuMemcpyDtoH
>   Args:   FPOS
> Error. Application will exit.

**Comment by davidxmiller** [comment]
I see the exact same output on my NVIDIA Quadro M1200

**Comment by TuotuoLi** [comment]
I am having the same problem here.

**Comment by YuxingQiu** [comment]
I have the same problem with you, and even the error log is the same. I'm testing on Windows 10 GTX 1070 Ti and the driver 411.63. My GPU memory is 8gb, while the program still crashed. T^T

**Comment by mrvanr** [comment]
Built on w10 with a Quadro M4000 using vs2015 and cuda 9.0 and getting the same error. The other samples work normally.

**Comment by kukuhbr** [comment]
Same problem with:
GTX1060,  win10+vs2015+cuda9.0+optix 4.0.0+driver 385.54

**Comment by shenberg** [comment]
Same problem with 1080Ti on ubuntu 18.04.

I did some comment-out debugging and noticed that the crash is caused by `CountingSortFullCUDA` - specifically, if I comment-out the call to the CUDA kernel doing the copying sort, I won't get a crash on `TransferFromCUDA()` (of course, the fluid simulation is not really running any more). I suspect a memory corruption but the code inside the kernel hasn't changed between 1.0 and 1.1 so I'm unsure as to the difference between the two versions.

One thing that I thought made a difference was that the number of threads per block was increased from 192 to 512 but changing it back did not make a difference.

**Comment by shenberg** [comment]
Found and fixed the bug. PR: https://github.com/NVIDIA/gvdb-voxels/pull/68
