### ISSUE TITLE
SolidVoxelize violation access with GLFW

### ISSUE THREAD

**Issue by jeremie-lg** [NVIDIA/gvdb-voxels#27]
I'm trying to use GLFW in place of NVPWindow because i want to run a voxelization in background without a window. I've made a naive initialization with a GLFWwindow, but i experienced a violation access at  SolidVoxelize(). Do i've missed something ?

VolumeGVDB gvdb;
glewInit();
glfwInit();

glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);

GLFWwindow* window = glfwCreateWindow(800, 600, "OpenGL", nullptr, nullptr); // Windowed
glfwMakeContextCurrent(window);

// Initialize GVDB
gvdb.SetDebug(true);
gvdb.SetVerbose(true);
gvdb.SetProfile(false, false);
gvdb.SetCudaDevice(GVDB_DEV_FIRST);
gvdb.Initialize();
gvdb.AddPath("../../source/shared_assets/");
gvdb.AddPath("../shared_assets/");
gvdb.AddPath(ASSET_PATH);
gvdb.StartRasterGL();

gvdb.getScene()->SetSteps(0.25f, 16.f, 0.25f);			// Set raycasting steps
gvdb.getScene()->SetVolumeRange(0.25f, 0.0f, 1.0f);		// Set volume value range
gvdb.getScene()->SetExtinct(-1.0f, 1.1f, 0.f);			       // Set volume extinction	
gvdb.getScene()->SetCutoff(0.005f, 0.005f, 0.f);
gvdb.getScene()->SetShadowParams(0, 0, 0);

int model_id = gvdb.getScene()->AddModel("lucy.obj", 1.0, 0, 0, 0);
gvdb.CommitGeometry(model_id);

Model* m = gvdb.getScene()->getModel(model_id);
Matrix4F xform;
Vector3DF voxelsize(0.2f, 0.2f, 0.2f);	// Voxel size (mm)
gvdb.SetVoxelSize(voxelsize.x, voxelsize.y, voxelsize.z);
gvdb.SolidVoxelize(0, m, &xform, 1.0, 0.5);

**Comment by Alvininorge** [comment]
have you tried inserting glGetError() in various places?

**Comment by jeremie-lg** [comment]
I also tried to set USE_GLFW ON in cmake but it changes anything.

**Comment by ramakarl** [comment]
I do not see AddChannel. You need that before SolidVoxelize.  -Rama

**Comment by jeremie-lg** [comment]
Oh sorry for my mistake, it works now ! thanks :)
