### ISSUE TITLE
timer for volume rendering incorrect in sample code

### ISSUE THREAD

**Issue by TuotuoLi** [NVIDIA/gvdb-voxels#28]
in the sample code:

	gvdb.TimerStart ();
	gvdb.Render ( SHADE_VOLUME, 0, 0 );
	float rtime = gvdb.TimerStop();
	nvprintf ( "Render volume. %6.3f ms\n", rtime );

It seems the call Render return before the actual ray casting was done.
Resulting measured sub millisecond performance which I was not expecting.
I think something needs to be add to wait for return of the operation on GPU.

**Comment by ramakarl** [comment]
You can put cuCtxSynchronize() immediately after gvdb.Render, before the timerstop.
However, that will also cause a GPU pipeline stall.
A better way would be to enable the NVIDIA NSight (nvtx) markers which are part of gvdb and use NSight to profile. This can do accurate timings w/o a wait stall.
