### ISSUE TITLE
Why isn't  the 3rd parameter of gvdbBrickFunc2_t passed by reference?

### ISSUE THREAD

**Issue by drmateo** [NVIDIA/gvdb-voxels#46]
Hi all,

I've been working in a modification of the raysurfaceTrilinearBrick function,

>  https://github.com/NVIDIA/gvdb-voxels/blob/25ed5f476792cb53dce44fde3852fc27d54fcd97/source/gvdb_library/kernels/cuda_gvdb_raycast.cuh#L226

used by the raycast function 

> https://github.com/NVIDIA/gvdb-voxels/blob/25ed5f476792cb53dce44fde3852fc27d54fcd97/source/gvdb_library/kernels/cuda_gvdb_raycast.cuh#L504

to render volumes. If the variable t which is used to go forward over the ray in the 3DDDA algorithm, my question is, why isn't  the 3rd parameter (float3 t) of gvdbBrickFunc2_t passed by reference when the algorithm is in level 1 of the tree (that is, processing brick level)? Changing this will make much more coherent the implementation regards with the algorithm since t once the method had explored the brick content, t will be pointing to the correct place, otherwise t keeps pointing to the last value in level 2.

The interface definition of these methods is write there,

> https://github.com/NVIDIA/gvdb-voxels/blob/25ed5f476792cb53dce44fde3852fc27d54fcd97/source/gvdb_library/kernels/cuda_gvdb_raycast.cuh#L34

**Comment by ramakarl** [comment]
Take a look at STEP_DDA which immediately follows the brickFunc call.
The next instruction there is t.x=t.y, which sets the t value to the exit point residing on the brick boundary as soon as brickFunc completes. Whereas the rayDeepBrick samples along dt, this is required for further DDA jumps at level 1.

There may be a variant of this approach which preserves the 't' value across bricks, making the deep volume sampling easier, but it must account for stepping across, up and down the tree also. I believe I experimented with this yet was unable to find a solution for rayCast that covered all scenarios. The current approach works for both deep and isosurface raytracing, and when the ray traces several side-by-side bricks, or if it has to jump across empty bricks and re-enter elsewhere.

**Comment by drmateo** [comment]
Oh! That is true. Thanks for your feedback
