### ISSUE TITLE
Compute total volume (reduction): Difference between atlas_cnt and atlas_res, layout of bricks in atlas

### ISSUE THREAD

**Issue by drmateo** [NVIDIA/gvdb-voxels#47]
I've created a simple kernel function to walk over the bricks in the atlas space with the objective of get statistics like mean, min and max value of each bricks. The kernel is launch by ComputeKernel method. This kernel bounds CUDA threads using atlas_cnt attribute of VDBInfo. To get node information of the current brick: first I generate bitmask_pos by getBitPos; and then, I get the node according las bitmask_pos and lev = 0. Using three concatenated loops I visit all voxels in the bricks (from atlas_apron to brick_res - 2*altas_apron). Each voxel access to the texture by tex(volIn, p.x + o.x, p.y+o.y, p.z+o.z) where o = node->mValue.

I'm not totally sure that this is working properly because I'm not sure about how are stored bricks in the atlas. I mean if all bricks in the atlas are contiguous then this strategy is fine because the kernel is bounded to the altas_cnt value which is the number of bricks stored (or what  is the same, it's pointing to the last birck stored). Otherwise I should use atlas_res which actually is the resolution of the atlas (but is this in the voxel level or brick level?)

I was looking for an answer in the programing guide, but there is not a clear one.

**Comment by alvingitlord** [comment]
I think bricks are densely allocated in atlas, you can launch a kernel with atlas_res on X and Y direction, evaluating voxels on Z direction in bricks that are flagged as used. Save the max or min of each column on a 2d array then use cudpp or other things to do a reduce.

**Comment by ramakarl** [comment]
This function already exists and is called gvdb.Reduction(). The kernel is gvdbReduction.

It does what Alvin suggests in 2D to scan along z, which is work efficient. 

I think your original question is about the layout of bricks, if there are some in the atlas that are not used. This is the case. The Reduction function assumes that the non-used brick regions have been pre-initialized to zero. This func could be modified or improved to retrieve the min and max also.

**Comment by alvingitlord** [comment]
Yes, the only small issue I had with gvdb.Reduction was that it still memcpy the 2d array back to host and follows a double for loop. say the atlas is 16*16*16, and brick_res = 5, then its a 2^13 number to loop through. Doesnt really make a difference in speed if you do that in CPU or GPU, but I wrapped that 2D Array in thrust::device_vector and called a reduce directly. Feels better that the gpu only throws back a single number.

**Comment by ramakarl** [comment]
@alvingitlord 
It might feel better that you get back a single number, but you dont know what cudpp is doing under the hood to give you that. For very large volumes i suspect cuddp reduction will be muvh slower.

I agree that the single brick case is an issue. A smarter reduction function would determine the minimum footprint of the atlas, bounding box in atlas space, and only access those by.limiting the threads and the max z height.

**Comment by drmateo** [comment]
Thanks for the replies. Yes,  my original question was about the bricks layout. I'll rewrite the code to base it in the gvdb.Reduction function, it will fit better for my porpose. But anyway, also I was looking for an answer to the question " are bricks densely allocated in atla?" so thanks too to @alvingitlord for your answer.

:+1:  for the new title
