### ISSUE TITLE
no kernel image is available  for execution on the device

### ISSUE THREAD

**Issue by bigdimboom** [NVIDIA/gvdb-voxels#49]
Does any one know what the issue is.  I'm running the pointCloud example
Cuda 9.2
Optix 5.11
laptop gpu GTX680m
VS2017
![image](https://user-images.githubusercontent.com/6119906/52028363-c2232900-24dc-11e9-8c91-7337f6710584.png)

**Comment by NeilBickford-NV** [comment]
Hi bigdimboom,

Closing this issue for now since it looks like a CUDPP issue (and as you saw in the other issue, version 1.1.1 removes CUDPP) - please feel free to reopen this issue if you have any problems building and running the `pointCloud` sample now. Thanks again for posting this!
