### ISSUE TITLE
All cuda kernel invocations fail with "unspecified launch failure" after a call to VolumeGVDB::Render

### ISSUE THREAD

**Issue by tnikodym** [NVIDIA/gvdb-voxels#69]
Below is the error log captured with cuda-memcheck: 

```
========= CUDA-MEMCHECK
Starting GVDB Voxels. ver 1.11
GVDB CUDA ERROR:
  Launch status: unspecified launch failure
  Kernel status: no error
  Caller: Allocator::RetrieveMem
  Call:   cuMemcpyDtoH
  Args:
Error. Application will exit.
========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to "unspecified launch failure" on CUDA API call to cuMemcpyDtoH_v2.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:C:\windows\SYSTEM32\nvcuda.dll (cuMemcpyPeer_ptds + 0x1cdc1d) [0x1dd45c]
=========     Host Frame:libgvdb.dll (nvdb::Vector4DF::Random + 0x8d) [0x9fdd]
=========     Host Frame:libgvdb.dll (nvdb::VolumeGVDB::ReadRenderBuf + 0x59) [0x40699]
=========     Host Frame:ConsoleRunner.exe (VolumeRenderer::renderToBuffer + 0x97) [0x177aa7]
=========     Host Frame:ConsoleRunner.exe (main + 0x915) [0x1a8a65]
=========     Host Frame:ConsoleRunner.exe (invoke_main + 0x34) [0x1805f4]
=========     Host Frame:ConsoleRunner.exe (__scrt_common_main_seh + 0x127) [0x180497]
=========     Host Frame:ConsoleRunner.exe (__scrt_common_main + 0xe) [0x18035e]
=========     Host Frame:ConsoleRunner.exe (mainCRTStartup + 0x9) [0x180619]
=========     Host Frame:C:\windows\System32\KERNEL32.DLL (BaseThreadInitThunk + 0x14) [0x14034]
=========     Host Frame:C:\windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x21) [0x73691]
=========
========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to "unspecified launch failure" on CUDA API call to cuModuleUnload.
```

I wasn't able to consistently reproduce the issue - when I re-run the same binary after a failure, it usually works fine. 

CUDA version: V10.1.105
GVDB Voxels version: 1.1

**Comment by icoderaven** [comment]
That is generally indicative of issues in implementation. Make sure you're allocating the correct number of bytes (the API can be slightly confusing at times) for your GPU memory. Since it seems to be in RenderBuf, the first thing I'd check is if your CPU pointer is h*w*4*sizeof(uchar) bytes.

**Comment by tnikodym** [comment]
I worked around the issue by increasing `course_dt` argument of `SetSteps`. However, I still believe there's an issue in GVDB, so I'll share more details. 

**Summary of observed behavior:** after a call to VolumeGVDB::Render with SHADE_VOLUME and high voxel count, high render buffer resolution and small step, any subsequent cuda kernel invocation fails with "unspecified launch failure". 

The following configuration consistently causes the issue above: 
Volume resolution: 224x224x244
Render buffer resolution: 2048x1536
Steps: SetSteps( 0.1f, 16, 0.1f )
Shade mode: SHADE_VOLUME

When I decrease volume resolution to 223x223x233 (or adjust any of the other three options above), it works without issues.

**Comment by ramakarl** [comment]
There is generally no reason to set the render steps below around 0.25. At 0.1 this means the sampling is 1/10th the size of a voxel, so all you are doing is accumulating interpolated data that doesnt add much detail. If you compare images at 0.25 to 0.5 you should still see little difference (subtract the two images)

Problems at 0.1 may be due to several things. Possibly the max iter is being hit, which is set to 256 steps. Possibly the kernel run time is reaching the driver kernel timeout, which is a few seconds. There is not much reason to set steps much below 0.25

**Comment by tnikodym** [comment]
The value of 0.1 comes from GVDB Programming Guide 1.1: _"Typically course and fine might be set the same, with values of 0.1 for highest quality."_ But you are right, there's very little visual difference between 0.25 and anything lower. 

While I have all the info I need to proceed with the work on my side, I would consider improving the error handling on GVDB side and throwing more descriptive errors when the API is misused. The _"unspecified launch failure"_ error makes it quite tricky to troubleshoot.
