### ISSUE TITLE
ActivateSpace Crashes on -ve coordinates

### ISSUE THREAD

**Issue by ramsampath** [NVIDIA/gvdb-voxels#7]
calling gvdb.ActivateSpace( v ) with any of v.x , v.y or v.z being negative seems to crash. Maybe its the order that I am calling methods. Can send an example if needed.

**Comment by djspecialagent** [comment]
Correct. Programming Guide specifically says this will happen. You much use
positive coordinates in GVDB 1.0.

**Comment by vsheihu** [comment]
However, gvdb1.1 still hasn't solved this problem.
