### ISSUE TITLE
Crash on win10, cuda 10.1

### ISSUE THREAD

**Issue by chena1982** [NVIDIA/gvdb-voxels#70]
win10, cuda 10.1, memory 32G.
C:\GitHub\gvdb-voxels\source\shared_cudpp\src\cudpp\app\reduce_app.cu line 176
call cudaMalloc, will run out of system memory, the used system memory is up to 32G, and the application will crash.

So how cloud i debug this problem?
If have some plane to test on win10, cuda 10.1?
Thanks.

**Comment by nathanchrs** [comment]
Hi @chena1982,

Can you give more details - what code are you trying to run? What GPU are you using?

**Comment by chena1982** [comment]
Hi @nathanchrs
I just want to init the gvdb.

![image](https://user-images.githubusercontent.com/5953033/59112275-45fe8d80-8975-11e9-8e75-e7aedcbfe1b1.png)

GPU is 980Ti.

**Comment by nathanchrs** [comment]
It seems that this is an issue with CUDPP and CUDA 10: [CUDPP issue #185](https://github.com/cudpp/cudpp/issues/185). This might also be related to #34.

For the time being, maybe you can downgrade to CUDA 9 as a workaround?

**Comment by johoe** [comment]
Hi, I postet a solution [here](https://devtalk.nvidia.com/default/topic/1036887/gvdb-voxels/cudpp-memory-leaking/post/5357275/#5357275). 
The problem arises from the __shfl functions, you can either replace all __shfl function of cudpp with its corresponding sync version or use compute capability less than 6.0

**Comment by chena1982** [comment]
@johoe Thanks for your share.
I replace the __shfl and __shfl_up in H:\gvdb-voxels-master\source\shared_cudpp\src\cudpp\kernel\multisplit_kernel.cuh and H:\gvdb-voxels-master\source\shared_cudpp\ext\moderngpu\include\device\intrinsics.cuh.
But it still don't work.

**Comment by johoe** [comment]
Hi @chena1982, we had to modify these files:

- gvdb-voxels/shared_cudpp/ext/cub/cub/util_ptx.cuh
- gvdb-voxels/shared_cudpp/ext/cub/cub/warp/specializations/warp_scan_shfl.cuh
- gvdb-voxels/shared_cudpp/ext/moderngpu/include/device/intrinsics.cuh
- gvdb-voxels/shared_cudpp/src/cudpp/kernel/multisplit_kernel.cuh

I commited my changes to [here](https://github.com/johoe/gvdb-voxels/tree/master/source/shared_cudpp). You may have a look.

**Comment by chena1982** [comment]
@johoe it works now.
Thanks.

**Comment by jhwang7628** [comment]
Thanks for all the help. @johoe I am worried about the other deprecated functions used in multisplit_kernel function (`cub` and `moderngpu` seemed to be patched now). In particular, my MVCC compiler is issuing warnings about deprecated intrinsics about

- __ballot
- instruction 'vote' (`warning : Instruction 'vote' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version`)

I am curious if you ran into any problem with these? Should we patch them as well?
