### ISSUE TITLE
Grid bricks appear to cast shadows in Optix

### ISSUE THREAD

**Issue by digbeta** [NVIDIA/gvdb-voxels#93]
Below is a scene consisting of a single GVDB volume bunny in the foreground with a cube mesh in the background.   The bottom left corner is an Optix preview of the scene and the main screen shows normal GVDB scene rendering.  Note the space in the top right of the Optix preview is lighter than the shadows that appear to be cast from the bricks against the mesh.

![image](https://user-images.githubusercontent.com/17113489/85067131-2ef49d00-b17e-11ea-9e17-3ef98ac9d733.png)

Looking more closely at the cube mesh, you can see it appears that the occupied brick is actually casting a shadow against the side of the box mesh:

![image](https://user-images.githubusercontent.com/17113489/85149669-8eef5000-b21f-11ea-8396-47666be98989.png)

Then I disable shadow rays in the Optix surface intersector program for the mesh geometry:

```
#if 0  //debug - disable shadow rays
	if (rayinfo.depth < SHADOW_DEPTH) {
		// shadow sample		
		for (int i = 0; i < 2; i++) {
			lightdir = normalize(normalize(light_pos - fhp) + jitter_sample() * mat.light_width);
			shadowclr *= TraceRay(fhp + lightdir*mat.shadow_bias, lightdir, rayinfo.depth + 1, SHADOW_RAY, refldist);
		}
	}
#endif
```
And here's what I get as a result:

![image](https://user-images.githubusercontent.com/17113489/85067370-93176100-b17e-11ea-9824-44c7a6d7f194.png)

Note the bricks no longer appear to cast shadows against the mesh.

Any ideas what might be happening?  Thanks in advance!

**Comment by NeilBickford-NV** [comment]
Hi digbeta!

I think the bugs in SetTransform and in OptiX should be fixed now - does this happen to fix this issue? (See main comment at https://github.com/NVIDIA/gvdb-voxels/issues/89#issuecomment-656899431.)

Thanks!

**Comment by digbeta** [comment]
Hi, Neil!

You’ve been busy!  I just saw all the great updates... I will dive into
these on Monday and will report back to its any issues!

Thanks again!

**Comment by digbeta** [comment]
This issue appears to have been resolved in the latest batch of fixes.  Closing the issue.  Thank you!
